#!/bin/sh

set -e

cd /opt/ld/ai-configs-intro/terraform/codecontrol-02
echo "project_key = \"${LD_PROJECT_KEY}\"" > terraform.tfvars
terraform init -input=false
terraform apply -auto-approve

python3 /opt/ld/ai-configs-intro/terraform/codecontrol-02/patch-server.py

service togglewear restart

exit 0
